package com.stanzom.domain.pundit.dto;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

public record PunditPostDto(
        UUID id,
        UUID userId,
        String userName,
        UUID eventId,
        String takeText,
        String audienceType,
        int likesCount,
        boolean isAutoGenerated,
        BigDecimal userAccuracy,
        Integer userRankAtPost,
        OffsetDateTime createdAt,
        List<PunditPostPickDto> picks
) {
}
