package com.stanzom.domain.pundit;

import com.stanzom.domain.pundit.dto.*;
import com.stanzom.domain.sport.Sport;
import com.stanzom.domain.sport.SportRepository;
import com.stanzom.shared.ResourceNotFoundException;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class PunditService {

    private final PunditPostRepository punditPostRepository;
    private final PunditPostPickRepository punditPostPickRepository;
    private final PunditPostLikeRepository punditPostLikeRepository;
    private final PunditMapper punditMapper;
    private final SportRepository sportRepository;

    public Page<PunditPostDto> getPunditPosts(UUID eventId, String sportSlug, String filter, Pageable pageable) {
        String resolvedFilter = (filter == null || filter.isBlank()) ? "ALL" : filter.toUpperCase();

        UUID sportId = null;
        if (sportSlug != null) {
            sportId = sportRepository.findBySlug(sportSlug)
                    .map(Sport::getId)
                    .orElse(null);
        }

        return punditPostRepository.findWithFilters(eventId, sportId, resolvedFilter, pageable)
                .map(post -> {
                    List<PunditPostPick> picks = punditPostPickRepository.findByPostId(post.getId());
                    List<PunditPostPickDto> pickDtos = punditMapper.toPickDtoList(picks);
                    PunditPostDto dto = punditMapper.toDto(post);
                    return new PunditPostDto(
                            dto.id(),
                            dto.userId(),
                            null, // userName resolved separately if needed
                            dto.eventId(),
                            dto.takeText(),
                            dto.audienceType(),
                            dto.likesCount(),
                            dto.isAutoGenerated(),
                            dto.userAccuracy(),
                            dto.userRankAtPost(),
                            dto.createdAt(),
                            pickDtos
                    );
                });
    }

    @Transactional
    public PunditPostDto createPost(UUID userId, CreatePunditPostRequest request) {
        PunditPost post = PunditPost.builder()
                .userId(userId)
                .eventId(request.eventId())
                .sportId(request.sportId())
                .takeText(request.takeText())
                .audienceType(request.audienceType() != null ? request.audienceType() : "PUBLIC")
                .isAutoGenerated(true)
                .build();

        post = punditPostRepository.save(post);

        // TODO: Auto-populate picks from user's predictions for the event

        List<PunditPostPick> picks = punditPostPickRepository.findByPostId(post.getId());
        List<PunditPostPickDto> pickDtos = punditMapper.toPickDtoList(picks);
        PunditPostDto dto = punditMapper.toDto(post);

        return new PunditPostDto(
                dto.id(),
                dto.userId(),
                null,
                dto.eventId(),
                dto.takeText(),
                dto.audienceType(),
                dto.likesCount(),
                dto.isAutoGenerated(),
                dto.userAccuracy(),
                dto.userRankAtPost(),
                dto.createdAt(),
                pickDtos
        );
    }

    @Transactional
    public void likePost(UUID userId, UUID postId) {
        PunditPost post = punditPostRepository.findById(postId)
                .orElseThrow(() -> new ResourceNotFoundException("PunditPost", "id", postId.toString()));

        if (punditPostLikeRepository.existsByPostIdAndUserId(postId, userId)) {
            return;
        }

        PunditPostLike like = PunditPostLike.builder()
                .postId(postId)
                .userId(userId)
                .build();
        punditPostLikeRepository.save(like);

        post.setLikesCount(post.getLikesCount() + 1);
        punditPostRepository.save(post);
    }

    @Transactional
    public void sharePost(UUID userId, UUID postId, SharePunditRequest request) {
        PunditPost post = punditPostRepository.findById(postId)
                .orElseThrow(() -> new ResourceNotFoundException("PunditPost", "id", postId.toString()));

        // TODO: Log share event and award points via RewardTransaction
    }
}
