package com.stanzom.domain.pundit;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

@Entity
@Table(name = "pundit_posts")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PunditPost {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(name = "event_id")
    private UUID eventId;

    @Column(name = "sport_id")
    private UUID sportId;

    @Column(name = "take_text", columnDefinition = "TEXT")
    private String takeText;

    @Column(name = "audience_type", length = 20)
    @Builder.Default
    private String audienceType = "PUBLIC";

    @Column(name = "likes_count")
    @Builder.Default
    private int likesCount = 0;

    @Column(name = "is_auto_generated")
    @Builder.Default
    private boolean isAutoGenerated = true;

    @Column(name = "user_accuracy")
    private BigDecimal userAccuracy;

    @Column(name = "user_rank_at_post")
    private Integer userRankAtPost;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;
}
