// ── Admin Roles ──────────────────────────────────────────────────────────────

export type AdminRole = 'SUPER_ADMIN' | 'ADMIN';

export interface Admin {
  id: string;
  name: string;
  email: string;
  role: AdminRole;
  permissions: string[];
  lastLogin: string;
  createdAt: string;
}

// ── Users ────────────────────────────────────────────────────────────────────

export interface User {
  id: string;
  name: string;
  email: string;
  phone?: string;
  avatar?: string;
  points: number;
  level: number;
  city?: string;
  state?: string;
  country?: string;
  referralCode: string;
  referredBy?: string;
  isActive: boolean;
  isVerified: boolean;
  createdAt: string;
  updatedAt: string;
}

// ── Sports & Tournaments ─────────────────────────────────────────────────────

export interface Sport {
  id: string;
  name: string;
  slug: string;
  icon?: string;
  isActive: boolean;
  sortOrder: number;
  createdAt: string;
}

export interface Tournament {
  id: string;
  name: string;
  slug: string;
  sportId: string;
  sport?: Sport;
  logo?: string;
  startDate: string;
  endDate: string;
  isActive: boolean;
  createdAt: string;
}

// ── Teams & Players ──────────────────────────────────────────────────────────

export interface Team {
  id: string;
  name: string;
  shortName: string;
  fullName?: string;
  logo?: string;
  sportId: string;
  sport?: Sport;
  tournamentId?: string;
  tournament?: Tournament;
  city?: string;
  homeGround?: string;
  primaryColor?: string;
  secondaryColor?: string;
  foundedYear?: number;
  titles?: number;
  country?: string;
  followersCount: number;
  rating: number;
  isActive: boolean;
  createdAt: string;
}

export interface Player {
  id: string;
  name: string;
  photo?: string;
  teamId: string;
  team?: Team;
  sportId: string;
  sport?: Sport;
  role?: string;
  position?: string;
  nationality?: string;
  jerseyNumber?: number;
  bio?: string;
  imageUrl?: string;
  followersCount: number;
  rating: number;
  isActive: boolean;
  createdAt: string;
}

// ── Events ───────────────────────────────────────────────────────────────────

export interface Event {
  id: string;
  title: string;
  sportId: string;
  sport?: Sport;
  tournamentId: string;
  tournament?: Tournament;
  homeTeamId: string;
  homeTeam?: Team;
  awayTeamId: string;
  awayTeam?: Team;
  startTime: string;
  endTime?: string;
  venue?: string;
  status: 'UPCOMING' | 'LIVE' | 'COMPLETED' | 'CANCELLED';
  homeScore?: number;
  awayScore?: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

// ── Predictions ──────────────────────────────────────────────────────────────

export interface PredictionQuestion {
  id: string;
  eventId: string;
  event?: Event;
  question: string;
  options: PredictionOption[];
  correctOptionId?: string;
  pointsReward: number;
  status: 'OPEN' | 'LOCKED' | 'RESOLVED' | 'CANCELLED';
  deadline: string;
  createdAt: string;
}

export interface PredictionOption {
  id: string;
  questionId: string;
  label: string;
  sortOrder: number;
}

export interface UserPrediction {
  id: string;
  userId: string;
  user?: User;
  questionId: string;
  question?: PredictionQuestion;
  selectedOptionId: string;
  isCorrect?: boolean;
  pointsEarned: number;
  createdAt: string;
}

// ── Polls ────────────────────────────────────────────────────────────────────

export interface Poll {
  id: string;
  question: string;
  options: PollOption[];
  sportId?: string;
  eventId?: string;
  totalVotes: number;
  isActive: boolean;
  expiresAt?: string;
  createdAt: string;
}

export interface PollOption {
  id: string;
  pollId: string;
  label: string;
  voteCount: number;
  sortOrder: number;
}

// ── Fan Rooms ────────────────────────────────────────────────────────────────

export interface FanRoom {
  id: string;
  name: string;
  eventId?: string;
  event?: Event;
  sportId: string;
  sport?: Sport;
  memberCount: number;
  isActive: boolean;
  createdAt: string;
}

// ── Pundit Posts ──────────────────────────────────────────────────────────────

export interface PunditPost {
  id: string;
  userId: string;
  user?: User;
  content: string;
  mediaUrl?: string;
  sportId?: string;
  sport?: Sport;
  eventId?: string;
  event?: Event;
  audienceType?: string;
  accuracy?: number;
  likesCount: number;
  commentsCount: number;
  isAutoGenerated: boolean;
  isFeatured: boolean;
  isHidden: boolean;
  picks?: PunditPick[];
  createdAt: string;
}

export interface PunditPick {
  id: string;
  postId: string;
  question: string;
  selectedOption: string;
  isCorrect?: boolean;
}

// ── Influencers ──────────────────────────────────────────────────────────────

export interface Influencer {
  id: string;
  userId: string;
  user?: User;
  displayName: string;
  handle?: string;
  bio?: string;
  profileImage?: string;
  socialLinks?: Record<string, string>;
  niche?: string[];
  platform?: string;
  followersCount: number;
  isVerified: boolean;
  isFeatured: boolean;
  featuredOrder?: number;
  rating: number;
  sportId?: string;
  sport?: Sport;
  isActive: boolean;
  createdAt: string;
}

export interface InfluencerApplication {
  id: string;
  userId: string;
  user?: User;
  displayName: string;
  bio: string;
  socialHandle?: string;
  niche?: string[];
  socialLinks: Record<string, string>;
  followerCount?: number;
  reason: string;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  rejectionReason?: string;
  reviewedAt?: string;
  stanzomStats?: {
    predictionAccuracy: number;
    totalPoints: number;
    activeDays: number;
  };
  createdAt: string;
}

// ── Rewards & Referrals ──────────────────────────────────────────────────────

export interface RewardTransaction {
  id: string;
  userId: string;
  user?: User;
  type: 'PREDICTION' | 'REFERRAL' | 'SHARE' | 'DAILY_LOGIN' | 'ACHIEVEMENT' | 'PRIZE' | 'ADMIN_ADJUSTMENT';
  points: number;
  description: string;
  referenceId?: string;
  createdAt: string;
}

export interface Referral {
  id: string;
  referrerId: string;
  referrer?: User;
  refereeId: string;
  referee?: User;
  pointsAwarded: number;
  createdAt: string;
}

export interface ShareLog {
  id: string;
  userId: string;
  user?: User;
  platform: string;
  contentType: string;
  contentId: string;
  pointsAwarded: number;
  createdAt: string;
}

// ── Sentiment ────────────────────────────────────────────────────────────────

export interface SentimentVote {
  id: string;
  userId: string;
  eventId: string;
  teamId: string;
  sentiment: 'POSITIVE' | 'NEGATIVE' | 'NEUTRAL';
  createdAt: string;
}

// ── Prizes ───────────────────────────────────────────────────────────────────

export interface DailyPrize {
  id: string;
  eventId: string;
  event?: Event;
  winnerId?: string;
  winner?: User;
  prizeName: string;
  prizeValue?: number;
  status: 'PENDING' | 'DRAWN' | 'CLAIMED' | 'DELIVERED' | 'EXPIRED';
  drawnAt?: string;
  createdAt: string;
}

export interface PrizeDeliveryAddress {
  id: string;
  prizeId: string;
  prize?: DailyPrize;
  userId: string;
  user?: User;
  fullName: string;
  addressLine1: string;
  addressLine2?: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  phone: string;
  amazonOrderId?: string;
  deliveryStatus: 'PENDING' | 'ORDERED' | 'SHIPPED' | 'DELIVERED';
  createdAt: string;
}

// ── Notifications ────────────────────────────────────────────────────────────

export interface Notification {
  id: string;
  target: 'ALL' | 'SEGMENT' | 'USER';
  targetId?: string;
  title: string;
  body: string;
  template?: string;
  sentAt: string;
  sentBy: string;
  recipientCount: number;
  createdAt: string;
}

// ── Dashboard KPIs ───────────────────────────────────────────────────────────

export interface DashboardKPIs {
  dau: number;
  dauTrend: number[];
  newInstallsToday: number;
  newInstallsWeek: number;
  predictionsToday: number;
  pointsIssuedToday: number;
  topCities: { city: string; count: number }[];
  referralConversion: number;
  sharesByPlatform: Record<string, number>;
  sportEngagement: { sport: string; percent: number }[];
}

// ── API Response Wrappers ────────────────────────────────────────────────────

export interface ApiResponse<T> {
  success: boolean;
  message: string;
  data: T;
}

export interface PaginatedResponse<T> extends ApiResponse<T> {
  page: number;
  size: number;
  totalPages: number;
  totalElements: number;
}
